create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  place text not null,
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  status text not null default '已读' check (status in ('已读', '在读')),
  note text default '',
  created_at timestamptz not null default now()
);

alter table public.books enable row level security;

create policy "Anyone can read books"
on public.books for select
to anon
using (true);

create policy "Anyone can add books"
on public.books for insert
to anon
with check (true);

create policy "Anyone can delete books"
on public.books for delete
to anon
using (true);